services:
  postgres:
    image: postgres:16
    container_name: order_store
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_store_db
    ports:
      - "5437:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ./
    container_name: order_service
    ports:
      - "8085:8085"
      - "5005:5005"
    depends_on:
      postgres:
        condition: service_started
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: order_store_db
      DB_USER: postgres
      DB_PASSWORD: postgres

volumes:
  pgdata:
