services:
  postgres:
    image: postgres:16
    container_name: authorization_server
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authorization_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ./
    container_name: authorization-server
    ports:
      - "9000:9000"
    depends_on:
      postgres:
        condition: service_started
    environment:
      DB_HOST: postgres
      DB_PORT: 5435
      DB_NAME: authorization_db
      DB_USER: postgres
      DB_PASSWORD: postgres

volumes:
  pgdata:
