apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: dasi-secrets
                  key: AUTH_DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: dasi-secrets
                  key: AUTH_DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: dasi-secrets
                  key: AUTH_DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: dasi-secrets
                  key: AUTH_DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dasi-secrets
                  key: AUTH_DB_PASSWORD
