apiVersion: v1
kind: Service
metadata:
  name: auth-postgres-service
spec:
  selector:
    app: auth-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30084
  type: NodePort