apiVersion: apps/v1
kind: Deployment
metadata:
  name: dasi-app
  labels:
    app: dasi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dasi
  template:
    metadata:
      labels:
        app: dasi
    spec:
      containers:
      - name: dasi-app
        image: ghcr.io/commin4u/dasi-app:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: dasi-config
        - secretRef:
            name: dasi-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      imagePullSecrets:
        - name: ghcr-secret
