apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: inventory-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: dasi-secrets
                  key: INVENTORY_DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: dasi-secrets
                  key: INVENTORY_DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: dasi-secrets
                  key: INVENTORY_DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: dasi-secrets
                  key: INVENTORY_DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dasi-secrets
                  key: INVENTORY_DB_PASSWORD
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: dasi-secrets
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: dasi-secrets
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: dasi-secrets
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dasi-secrets
                  key: RABBITMQ_PASSWORD
