apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30083
