apiVersion: v1
kind: Service
metadata:
  name: order-postgres-service
spec:
  selector:
    app: order-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30086
  type: NodePort