name: CI/CD Pipeline

on:
  push: {}
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: dasi-app
  DOCKER_REGISTRY: ghcr.io

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Tests
        run: ./gradlew test --info --stacktrace
        working-directory: inventory

      - name: Build Application
        run: ./gradlew build --info --stacktrace
        working-directory: inventory

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: inventory/build/test-results/**/*.xml

  deploy-infrastructure:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: List Terraform Directory
        run: ls -la infrastructure/terraform

      - name: Terraform Init
        run: terraform -chdir=infrastructure/terraform init -input=false

      - name: Terraform Plan
        run: terraform -chdir=infrastructure/terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=infrastructure/terraform apply -auto-approve -input=false

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Normalize repository name to lowercase
        run: echo "REPO_LOWERCASE=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t $DOCKER_REGISTRY/$REPO_LOWERCASE/$DOCKER_IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push $DOCKER_REGISTRY/$REPO_LOWERCASE/$DOCKER_IMAGE_NAME:${{ github.sha }}

